export const serviceTitleTemplates = [
  `Professional {service} Services: Expert Solutions You Can Trust`,
  `{service} Excellence: Industry-Leading Solutions`,
  `Premium {service} Services: Quality That Exceeds Expectations`,
  `{service} Specialists: Your Trusted Industry Partner`,
  `Advanced {service} Solutions: Innovation Meets Experience`,
  `{service} Experts: Setting the Industry Standard`,
  `Certified {service} Services: Professional Excellence Guaranteed`,
  `{service} Solutions: Where Quality Meets Reliability`,
  `Elite {service} Services: Exceeding Industry Standards`,
  `{service} Professionals: Your Success Is Our Priority`,
  `{service} Excellence: Proven Results, Trusted Experience`,
  `Premier {service} Services: Industry-Leading Solutions`,
  `{service} Solutions: Excellence in Every Detail`,
  `{service} Specialists: Trusted Industry Leaders`,
  `{service} Services: Innovation That Drives Success`,
  `{service} Excellence: Setting New Industry Standards`,
  `{service} Solutions: Where Experience Meets Innovation`,
  `{service} Services: Professional Excellence Delivered`,
  `{service} Experts: Your Partner in Success`,
  `{service} Solutions: Quality That Speaks for Itself`,
  `{service} Services: Excellence Through Innovation`,
  `{service} Specialists: Industry-Leading Expertise`,
  `{service} Excellence: Professional Solutions That Work`,
  `{service} Services: Your Vision, Our Expertise`,
  `{service} Solutions: Quality Without Compromise`,
  `{service} Experts: Excellence in Every Project`,
  `{service} Services: Innovation That Delivers Results`,
  `{service} Solutions: Professional Excellence Guaranteed`,
  `{service} Specialists: Your Success Story Starts Here`,
  `{service} Excellence: Where Quality Meets Innovation`,
  `{service} Services You Can Trust`,
  `Reliable {service} Solutions`,
  `Affordable {service} Services`,
  `Expert {service} Specialists`,
  `Quality {service} Services`,
  `Trusted {service} Experts`,
  `{service} Services Guaranteed`,
  `Dependable {service} Solutions`,
  `Top {service} Services`,
  `{service} Professionals at Your Service`,
  `Proven {service} Results`,
  `Best {service} Services`,
  `Efficient {service} Solutions`,
  `Experienced {service} Leaders`,
  `{service} Services for Your Needs`,
  `New Standards in {service}`,
  `Innovative {service} Solutions`,
  `Professional {service} Services`,
  `{service} Experts Helping You`,
  `Quality {service} You Deserve`,
  `{service} Services Done Right`,
  `Industry-Trusted {service} Experts`,
  `Effective {service} Solutions`,
  `Your {service} Partner`,
  `Top-Notch {service} Services`,
  `Reliable {service} Professionals`,
  `Affordable {service} Solutions`,
  `Trusted {service} Providers`,
  `Quality {service} Guaranteed`,
  `Expert {service} Services`,
  `{service} Solutions You Need`,
  `Dependable {service} Professionals`,
  `{service} Services Made Easy`,
  `Efficient {service} Experts`,
  `Pro {service} Services`,
  `Your Trusted {service} Team`,
  `Reliable {service} Providers`,
  `Quality {service} Experts`,
  `Affordable {service} Providers`,
  `Trusted {service} Team`,
  `Expert {service} Providers`,
  `Professional {service} Experts`,
  `Dependable {service} Team`,
  `{service} Services You Need`,
  `Effective {service} Experts`,
  `Top {service} Professionals`,
  `{service} Solutions You Can Count On`,
  `Reliable {service} Team`,
  `Quality {service} Professionals`,
  `Affordable {service} Experts`,
  `Trusted {service} Team`,
  `Expert {service} Solutions`
];

export const locationTitleTemplates = [
  `{service} Services in {location}: Your Local Industry Experts`,
  `{location}'s Premier {service} Solutions Provider`,
  `Professional {service} Services Serving {location} Community`,
  `{service} Excellence in {location}: Local Expertise, Global Standards`,
  `{location}'s Trusted {service} Specialists`,
  `{service} Solutions for {location}: Local Experience Matters`,
  `Expert {service} Services Throughout {location}`,
  `{location}'s Leading {service} Service Provider`,
  `{service} Excellence: Serving {location} with Pride`,
  `{service} Specialists in {location}: Your Local Partner`,
  `{location}'s Choice for Professional {service} Services`,
  `{service} Solutions: Local Expertise in {location}`,
  `{service} Services: {location}'s Trusted Choice`,
  `Professional {service} Solutions in {location}`,
  `{location}'s Expert {service} Service Provider`,
  `{service} Excellence: Local Solutions in {location}`,
  `{service} Services: Your {location} Industry Leader`,
  `{location}'s Professional {service} Solutions`,
  `{service} Specialists: Serving {location} Community`,
  `{service} Excellence in Greater {location}`,
  `{location}'s Dedicated {service} Service Provider`,
  `{service} Solutions: Local Expertise, Global Standards`,
  `{service} Services: {location}'s Industry Leader`,
  `Professional {service} Excellence in {location}`,
  `{location}'s Complete {service} Solutions Provider`,
  `{service} Services: Local Experience in {location}`,
  `{service} Excellence: Your {location} Solution`,
  `{location}'s Professional {service} Specialists`,
  `{service} Solutions: Trusted in {location}`,
  `{service} Services: {location}'s Premier Choice`
    `{service} Services in {location}`,
  `Reliable {service} in {location}`,
  `Affordable {service} in {location}`,
  `Expert {service} in {location}`,
  `Trusted {service} Providers in {location}`,
  `Quality {service} in {location}`,
  `Top {service} in {location}`,
  `Professional {service} in {location}`,
  `Best {service} in {location}`,
  `{service} Experts in {location}`,
  `Dependable {service} in {location}`,
  `Efficient {service} in {location}`,
  `{service} Solutions in {location}`,
  `Experienced {service} in {location}`,
  `Your {service} Partner in {location}`,
  `Reliable {service} Providers in {location}`,
  `Affordable {service} Solutions in {location}`,
  `Trusted {service} in {location}`,
  `Quality {service} Providers in {location}`,
  `Expert {service} Solutions in {location}`,
  `Top-Quality {service} in {location}`,
  `Professional {service} Providers in {location}`,
  `Best {service} Providers in {location}`,
  `Efficient {service} Solutions in {location}`,
  `Dependable {service} Providers in {location}`,
  `Experienced {service} Providers in {location}`,
  `{service} Experts Serving {location}`,
  `Reliable {service} Services in {location}`,
  `Affordable {service} Providers in {location}`,
  `Trusted {service} Experts in {location}`,
  `Quality {service} Solutions in {location}`,
  `Expert {service} Providers in {location}`,
  `Top {service} Providers in {location}`,
  `Professional {service} Experts in {location}`,
  `Best {service} Solutions in {location}`,
  `Efficient {service} Providers in {location}`,
  `Dependable {service} Experts in {location}`,
  `Experienced {service} Solutions in {location}`,
  `{service} Services for {location}`,
  `Reliable {service} Experts in {location}`,
  `Affordable {service} Experts in {location}`,
  `Trusted {service} Solutions in {location}`,
  `Quality {service} Experts in {location}`,
  `Expert {service} Solutions for {location}`,
  `Top {service} Experts in {location}`,
  `Professional {service} Solutions in {location}`,
  `Best {service} Experts in {location}`,
  `Efficient {service} Experts in {location}`,
  `Dependable {service} Solutions in {location}`,
];

export const blogTitleTemplates = [
  `The Ultimate Guide to {service} in {location}: Expert Insights`,
  `{service} Best Practices: A Comprehensive Guide for {location}`,
  `{location} {service} Guide: Professional Tips and Strategies`,
  `Mastering {service} in {location}: Expert Recommendations`,
  `{service} Solutions: Essential Tips for {location} Success`,
  `The Complete {service} Handbook for {location} Businesses`,
  `{service} Excellence: A {location} Success Story`,
  `Innovative {service} Strategies for {location} Growth`,
  `{service} Insights: {location}'s Professional Guide`,
  `Maximizing {service} Success in {location}: Expert Guide`,
  `{service} Solutions: {location}'s Comprehensive Resource`,
  `Advanced {service} Techniques for {location} Success`,
  `{service} Mastery: Essential Guide for {location}`,
  `{location}'s Guide to Professional {service} Success`,
  `{service} Excellence: Strategies for {location} Growth`,
  `The {location} Professional's Guide to {service}`,
  `{service} Innovation: {location}'s Success Blueprint`,
  `Essential {service} Practices for {location} Excellence`,
  `{service} Success Stories from {location}: A Guide`,
  `{location}'s Complete Resource for {service} Excellence`,
  `Professional {service} Insights: {location} Edition`,
  `{service} Solutions: The {location} Success Guide`,
  `Transforming {service} Success in {location}`,
  `{service} Best Practices: {location} Industry Guide`,
  `{location}'s Ultimate {service} Success Manual`,
  `{service} Excellence: The {location} Advantage`,
  `Strategic {service} Solutions for {location} Growth`,
  `{service} Innovation: {location}'s Expert Guide`,
  `{location}'s Professional Guide to {service} Success`,
  `{service} Mastery: {location}'s Complete Resource`
   `Guide to {service} in {location}`,
  `Top Tips for {service} in {location}`,
  `How to Improve Your {service} in {location}`,
  `Benefits of {service} in {location}`,
  `Common {service} Questions in {location}`,
  `Why Choose {service} in {location}`,
  `Steps to Get Better {service} in {location}`,
  `Understanding {service} in {location}`,
  `How {service} Helps in {location}`,
  `Best Practices for {service} in {location}`,
  `Tips for Maintaining {service} in {location}`,
  `How to Select {service} in {location}`,
  `Advantages of {service} in {location}`,
  `Effective {service} Strategies for {location}`,
  `How to Save on {service} in {location}`,
  `Essential {service} Tips for {location}`,
  `Improving {service} in {location}`,
  `Guide to Affordable {service} in {location}`,
  `How to Choose {service} in {location}`,
  `Steps for Quality {service} in {location}`,
  `Understanding the Importance of {service} in {location}`,
  `How {service} Can Benefit Your {location} Home`,
  `Best {service} Solutions for {location}`,
  `Effective Ways to Use {service} in {location}`,
  `How to Enhance Your {service} in {location}`,
  `Top {service} Trends in {location}`,
  `How to Get the Best {service} in {location}`,
  `Common Mistakes in {service} and How to Avoid Them in {location}`,
  `Why {service} is Essential for {location}`,
  `How to Maintain Your {service} in {location}`,
  `Top Reasons to Invest in {service} in {location}`,
  `How {service} Improves {location} Businesses`,
  `Guide to Professional {service} in {location}`,
  `Tips for Effective {service} in {location}`,
  `How to Get Started with {service} in {location}`,
  `Benefits of Professional {service} in {location}`,
  `How {service} Can Save You Time in {location}`,
  `Top Features to Look for in {service} in {location}`,
  `How to Troubleshoot {service} Issues in {location}`,
  `The Importance of {service} for {location} Homes`,
  `How to Upgrade Your {service} in {location}`,
  `Understanding the Costs of {service} in {location}`,
  `How {service} Enhances Your {location} Property`,
  `Best Tools for {service} in {location}`,
  `How to Plan for {service} in {location}`,
  `Steps to Effective {service} in {location}`,
  `How {service} Contributes to {location} Safety`,
  `Guide to Sustainable {service} in {location}`,
];

export const getRandomTemplate = (templates: string[], replacements: Record<string, string>) => {
  const template = templates[Math.floor(Math.random() * templates.length)];
  return Object.entries(replacements).reduce(
    (str, [key, value]) => str.replace(new RegExp(`{${key}}`, 'g'), value),
    template
  );
};
