export const serviceTitleTemplates = [
  `Get Reliable {service} Services Today`,
  `Your Trusted Source for {service}`,
  `Affordable {service} Solutions Near You`,
  `Expert Help with {service}`,
  `Top Choice for {service} Needs`,
  `Professional {service} Services You Can Trust`,
  `Quality {service} at Great Prices`,
  `Experienced {service} Specialists Ready to Help`,
  `Quick and Easy {service} Solutions`,
  `Dependable {service} Services for Your Home`,
  `Simplify Your {service} Needs Today`,
  `Trusted {service} Professionals at Your Service`,
  `Exceptional {service} Services for You`,
  `Best {service} Services in Town`,
  `Friendly and Reliable {service} Experts`,
  `Your Go-To Team for {service} Services`,
  `Making {service} Simple and Stress-Free`,
  `High-Quality {service} Services Guaranteed`,
  `We're Here for Your {service} Needs`,
  `Choose Us for Top-Notch {service} Services`,
  `${service} Solutions Made Simple`,
  `Premium ${service} Services for Your Needs`,
  `Expert ${service} Services at Your Doorstep`,
  `Your Local ${service} Specialists`,
  `${service} Excellence Guaranteed`,
  `Custom ${service} Solutions`,
  `${service} Services You Can Count On`,
  `Leading Provider of ${service} Services`,
  `${service} Services Done Right`,
  `Superior ${service} Solutions`,
  `${service} Services with a Personal Touch`,
  `Professional ${service} Care`,
  `${service} Services: Quality You Deserve`,
  `Complete ${service} Solutions`,
  `${service} Services: Experience the Difference`,
  `Advanced ${service} Solutions`,
  `${service} Services: Your Satisfaction Guaranteed`,
  `${service} Excellence: Our Promise to You`,
  `${service} Services: Quality That Lasts`,
  `${service} Solutions for Every Need`,
  `${service} Services: Built on Trust`,
  `${service} Solutions: Tailored for You`,
  `${service} Services: Above and Beyond`,
  `${service} Excellence: Our Standard`,
  `${service} Services: The Professional Choice`,
  `${service} Solutions: Smart and Simple`,
  `${service} Services: Always Reliable`,
  `${service} Solutions: Expert Care`,
  `${service} Services: Your Best Choice`,
  `${service} Solutions: Quality First`,
  `${service} Services: Excellence Delivered`,
  `${service} Solutions: Trust the Experts`,
  `${service} Services: Setting the Standard`,
  `${service} Solutions: Professional Results`,
  `${service} Services: Customer Focused`,
  `${service} Solutions: Experience Matters`,
  `${service} Services: Quality Assured`,
  `${service} Solutions: Satisfaction Guaranteed`,
  `${service} Services: Excellence in Action`,
  `${service} Solutions: Proven Results`,
  `${service} Services: Your Trusted Partner`,
  `${service} Solutions: Quality Service`,
  `${service} Services: Professional Excellence`,
  `${service} Solutions: Reliable Results`,
  `${service} Services: Expert Solutions`,
  `${service} Solutions: Quality Care`,
  `${service} Services: Trust Our Experience`,
  `${service} Solutions: Professional Care`,
  `${service} Services: Excellence Every Time`,
  `${service} Solutions: Your Success, Our Priority`
];

export const locationTitleTemplates = [
  `Expert {service} Services in {location}`,
  `Your Go-To {service} Experts in {location}`,
  `Need {service} in {location}? We've Got You Covered`,
  `Fast and Reliable {service} Services in {location}`,
  `Top-Rated {service} Solutions in {location}`,
  `Trusted {service} Professionals Serving {location}`,
  `Quality {service} Services in {location}`,
  `Dependable {service} Help in {location} When You Need It`,
  `Experienced {service} Specialists in {location}`,
  `Your Local {service} Experts in {location}`,
  `Affordable {service} Services in {location}`,
  `Get the Best {service} in {location}`,
  `Reliable {service} Services Near You in {location}`,
  `Professional {service} Solutions in {location}`,
  `Top Choice for {service} Services in {location}`,
  `${service} Services Available in {location}`,
  `Local ${service} Experts in {location}`,
  `${service} Solutions for ${location} Residents`,
  `${location}'s Trusted ${service} Provider`,
  `${service} Services Throughout ${location}`,
  `${location}'s Choice for ${service} Services`,
  `${service} Excellence in ${location}`,
  `${service} Services Near You in ${location}`,
  `${location}'s Premier ${service} Provider`,
  `${service} Solutions in ${location} Area`,
  `${service} Services Across ${location}`,
  `${location}'s Favorite ${service} Company`,
  `${service} Experts Serving ${location}`,
  `${service} Solutions Available in ${location}`,
  `${location}'s Most Trusted ${service} Team`,
  `${service} Services for ${location} Community`,
  `${location}'s Leading ${service} Provider`,
  `${service} Excellence for ${location} Residents`,
  `${service} Solutions in Greater ${location}`,
  `${location}'s Top-Rated ${service} Services`,
  `${service} Experts in ${location} Area`,
  `${service} Services Throughout ${location} Region`,
  `${location}'s Professional ${service} Team`,
  `${service} Solutions for ${location} Area`,
  `${location}'s Reliable ${service} Provider`,
  `${service} Services in ${location} and Surrounding Areas`,
  `${location}'s Expert ${service} Team`,
  `${service} Solutions Near You in {location}`,
  `${location}'s Quality ${service} Services`,
  `${service} Excellence Throughout ${location}`,
  `${location}'s Trusted Name in ${service}`,
  `${service} Services for All of ${location}`,
  `${location}'s Experienced ${service} Team`,
  `${service} Solutions Across ${location}`,
  `${location}'s Professional ${service} Services`,
  `${service} Excellence in Greater ${location}`,
  `${location}'s Complete ${service} Solutions`,
  `${service} Services for ${location} Neighborhoods`,
  `${location}'s Premier ${service} Solutions`,
  `${service} Excellence for ${location} Community`,
  `${location}'s Comprehensive ${service} Services`,
  `${service} Solutions Throughout ${location}`,
  `${location}'s Dedicated ${service} Team`,
  `${service} Services for ${location} Area`,
  `${location}'s Superior ${service} Solutions`,
  `${service} Excellence Near You in {location}`,
  `${location}'s Trusted ${service} Solutions`,
  `${service} Services Across Greater ${location}`,
  `${location}'s Expert ${service} Solutions`,
  `${service} Excellence Throughout ${location} Region`
];

export const blogTitleTemplates = [
  `10 Essential Tips for {service} in {location}`,
  `7 Reasons to Choose Professional {service} Services in {location}`,
  `5 Common {service} Mistakes and How to Avoid Them`,
  `How to Get the Best {service} in {location}`,
  `A Step-by-Step Guide to {service} for {location} Homeowners`,
  `How to Save Money on {service} Services in {location}`,
  `{service} Options in {location}: DIY vs. Professional Services`,
  `Comparing Top {service} Providers in {location}`,
  `Case Study: Successful {service} Projects in {location}`,
  `Real-Life Examples of {service} Solutions in {location}`,
  `Why {service} is Essential for {location} Residents`,
  `The Importance of Quality {service} in {location}`,
  `An Interview with a {service} Expert in {location}`,
  `Insights from Experienced {service} Professionals in {location}`,
  `The Ultimate {service} Checklist for {location} Homeowners`,
  `The Ultimate Guide to ${service} in ${location}`,
  `${service} Tips Every ${location} Resident Should Know`,
  `Expert Advice: ${service} Solutions in ${location}`,
  `${location}'s Complete Guide to ${service}`,
  `Everything You Need to Know About ${service} in ${location}`,
  `${service} Essentials for ${location} Homeowners`,
  `Top ${service} Trends in ${location}`,
  `${service} Guide: What ${location} Residents Need to Know`,
  `Insider Tips for ${service} in ${location}`,
  `${service} Solutions: A Guide for ${location} Residents`,
  `Understanding ${service} Options in ${location}`,
  `${service} 101: A Guide for ${location}`,
  `Smart ${service} Solutions for ${location} Properties`,
  `${service} Basics: What ${location} Residents Should Know`,
  `${service} Tips and Tricks for ${location} Homes`,
  `The ${location} Guide to Quality ${service}`,
  `${service} Insights for ${location} Property Owners`,
  `Essential ${service} Knowledge for ${location}`,
  `${service} Best Practices in ${location}`,
  `${location}'s Guide to Professional ${service}`,
  `${service} Solutions: ${location} Expert Tips`,
  `Understanding ${service} Needs in ${location}`,
  `${service} Guide: ${location} Professional Advice`,
  `${location} Property Owner's Guide to ${service}`,
  `${service} Solutions: What ${location} Should Know`,
  `Expert ${service} Guide for ${location}`,
  `${service} Tips: A ${location} Perspective`,
  `${location}'s Comprehensive ${service} Guide`,
  `${service} Solutions: ${location} Best Practices`,
  `${service} Knowledge: Essential Tips for ${location}`,
  `${location}'s Ultimate ${service} Resource`,
  `${service} Guide: Insights for ${location}`,
  `${service} Solutions: ${location} Expert Guide`,
  `${location}'s Essential ${service} Tips`,
  `${service} Guide: Professional Tips for ${location}`,
  `${service} Solutions: ${location} Resident's Guide`,
  `${location}'s Complete ${service} Resource`,
  `${service} Tips: Expert Advice for ${location}`,
  `${location}'s Professional ${service} Guide`,
  `${service} Solutions: ${location} Homeowner's Guide`,
  `${service} Guide: ${location} Expert Insights`,
  `${location}'s Trusted ${service} Resource`,
  `${service} Solutions: Complete Guide for ${location}`,
  `${service} Tips: ${location} Professional Guide`,
  `${location}'s Definitive ${service} Resource`,
  `${service} Guide: Everything ${location} Should Know`,
  `${service} Solutions: ${location} Complete Guide`,
  `${location}'s Expert ${service} Resource`,
  `${service} Guide: ${location} Essential Tips`,
  `${service} Solutions: ${location} Master Guide`
];

export const getRandomTemplate = (templates: string[], replacements: Record<string, string>) => {
  const template = templates[Math.floor(Math.random() * templates.length)];
  return Object.entries(replacements).reduce(
    (str, [key, value]) => str.replace(new RegExp(`{${key}}`, 'g'), value),
    template
  );
};
