// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://wvvcsjwflxzbeavbaoli.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2dmNzandmbHh6YmVhdmJhb2xpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzIwMjY0NzcsImV4cCI6MjA0NzYwMjQ3N30.qS-iHQgoRPBacHMsiP9uvaUYHBmWkIYFTlbVk5VsKWY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);